// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR5arB6TQvPdvgDWd-4j8Q2k9zFzWTDGk',
    appId: '1:582609154062:web:2185c57ce2da011fbb8c5f',
    messagingSenderId: '582609154062',
    projectId: 'crumbles-fyp',
    authDomain: 'crumbles-fyp.firebaseapp.com',
    storageBucket: 'crumbles-fyp.appspot.com',
    measurementId: 'G-RBHMQSFQMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjuWAcQKSf1NT1RNzhR5oKcx79wsPjTKw',
    appId: '1:582609154062:android:d523aead9ff36734bb8c5f',
    messagingSenderId: '582609154062',
    projectId: 'crumbles-fyp',
    storageBucket: 'crumbles-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4m0NOCPrmGxPBBlhpPwawlOXPTinnwRM',
    appId: '1:582609154062:ios:8874af92882962b6bb8c5f',
    messagingSenderId: '582609154062',
    projectId: 'crumbles-fyp',
    storageBucket: 'crumbles-fyp.appspot.com',
    androidClientId: '582609154062-vo42jmdub9pb1fbpu6eukgvtamebio03.apps.googleusercontent.com',
    iosClientId: '582609154062-r2e1bs1sjt1ucg08c25m4mts5olfvl2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.crumbles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4m0NOCPrmGxPBBlhpPwawlOXPTinnwRM',
    appId: '1:582609154062:ios:8874af92882962b6bb8c5f',
    messagingSenderId: '582609154062',
    projectId: 'crumbles-fyp',
    storageBucket: 'crumbles-fyp.appspot.com',
    androidClientId: '582609154062-vo42jmdub9pb1fbpu6eukgvtamebio03.apps.googleusercontent.com',
    iosClientId: '582609154062-r2e1bs1sjt1ucg08c25m4mts5olfvl2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.crumbles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR5arB6TQvPdvgDWd-4j8Q2k9zFzWTDGk',
    appId: '1:582609154062:web:aa3bca8c08e7698ebb8c5f',
    messagingSenderId: '582609154062',
    projectId: 'crumbles-fyp',
    authDomain: 'crumbles-fyp.firebaseapp.com',
    storageBucket: 'crumbles-fyp.appspot.com',
    measurementId: 'G-QQP6CBR98M',
  );
}
